package com.wong.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wong.greendao.TableRecordGroup;
import com.wong.greendao.TableRecordPersonal;

import com.wong.greendao.TableRecordGroupDao;
import com.wong.greendao.TableRecordPersonalDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tableRecordGroupDaoConfig;
    private final DaoConfig tableRecordPersonalDaoConfig;

    private final TableRecordGroupDao tableRecordGroupDao;
    private final TableRecordPersonalDao tableRecordPersonalDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tableRecordGroupDaoConfig = daoConfigMap.get(TableRecordGroupDao.class).clone();
        tableRecordGroupDaoConfig.initIdentityScope(type);

        tableRecordPersonalDaoConfig = daoConfigMap.get(TableRecordPersonalDao.class).clone();
        tableRecordPersonalDaoConfig.initIdentityScope(type);

        tableRecordGroupDao = new TableRecordGroupDao(tableRecordGroupDaoConfig, this);
        tableRecordPersonalDao = new TableRecordPersonalDao(tableRecordPersonalDaoConfig, this);

        registerDao(TableRecordGroup.class, tableRecordGroupDao);
        registerDao(TableRecordPersonal.class, tableRecordPersonalDao);
    }
    
    public void clear() {
        tableRecordGroupDaoConfig.getIdentityScope().clear();
        tableRecordPersonalDaoConfig.getIdentityScope().clear();
    }

    public TableRecordGroupDao getTableRecordGroupDao() {
        return tableRecordGroupDao;
    }

    public TableRecordPersonalDao getTableRecordPersonalDao() {
        return tableRecordPersonalDao;
    }

}
