package com.wong.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.wong.greendao.TableRecordPersonal;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TABLE_RECORD_PERSONAL".
*/
public class TableRecordPersonalDao extends AbstractDao<TableRecordPersonal, Long> {

    public static final String TABLENAME = "TABLE_RECORD_PERSONAL";

    /**
     * Properties of entity TableRecordPersonal.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cloud_id = new Property(1, long.class, "cloud_id", false, "CLOUD_ID");
        public final static Property Detail = new Property(2, String.class, "detail", false, "DETAIL");
        public final static Property Money = new Property(3, float.class, "money", false, "MONEY");
        public final static Property Buy_time = new Property(4, java.util.Date.class, "buy_time", false, "BUY_TIME");
        public final static Property Category_id = new Property(5, Long.class, "category_id", false, "CATEGORY_ID");
        public final static Property Category_name = new Property(6, String.class, "category_name", false, "CATEGORY_NAME");
        public final static Property Buyer_id = new Property(7, Long.class, "buyer_id", false, "BUYER_ID");
        public final static Property Buyer = new Property(8, String.class, "buyer", false, "BUYER");
        public final static Property Kind = new Property(9, int.class, "kind", false, "KIND");
        public final static Property State = new Property(10, int.class, "state", false, "STATE");
        public final static Property Modify_time = new Property(11, java.util.Date.class, "modify_time", false, "MODIFY_TIME");
    };


    public TableRecordPersonalDao(DaoConfig config) {
        super(config);
    }
    
    public TableRecordPersonalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TABLE_RECORD_PERSONAL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CLOUD_ID\" INTEGER NOT NULL ," + // 1: cloud_id
                "\"DETAIL\" TEXT NOT NULL ," + // 2: detail
                "\"MONEY\" REAL NOT NULL ," + // 3: money
                "\"BUY_TIME\" INTEGER NOT NULL ," + // 4: buy_time
                "\"CATEGORY_ID\" INTEGER," + // 5: category_id
                "\"CATEGORY_NAME\" TEXT NOT NULL ," + // 6: category_name
                "\"BUYER_ID\" INTEGER," + // 7: buyer_id
                "\"BUYER\" TEXT NOT NULL ," + // 8: buyer
                "\"KIND\" INTEGER NOT NULL ," + // 9: kind
                "\"STATE\" INTEGER NOT NULL ," + // 10: state
                "\"MODIFY_TIME\" INTEGER NOT NULL );"); // 11: modify_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TABLE_RECORD_PERSONAL\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TableRecordPersonal entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCloud_id());
        stmt.bindString(3, entity.getDetail());
        stmt.bindDouble(4, entity.getMoney());
        stmt.bindLong(5, entity.getBuy_time().getTime());
 
        Long category_id = entity.getCategory_id();
        if (category_id != null) {
            stmt.bindLong(6, category_id);
        }
        stmt.bindString(7, entity.getCategory_name());
 
        Long buyer_id = entity.getBuyer_id();
        if (buyer_id != null) {
            stmt.bindLong(8, buyer_id);
        }
        stmt.bindString(9, entity.getBuyer());
        stmt.bindLong(10, entity.getKind());
        stmt.bindLong(11, entity.getState());
        stmt.bindLong(12, entity.getModify_time().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TableRecordPersonal readEntity(Cursor cursor, int offset) {
        TableRecordPersonal entity = new TableRecordPersonal( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // cloud_id
            cursor.getString(offset + 2), // detail
            cursor.getFloat(offset + 3), // money
            new java.util.Date(cursor.getLong(offset + 4)), // buy_time
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // category_id
            cursor.getString(offset + 6), // category_name
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // buyer_id
            cursor.getString(offset + 8), // buyer
            cursor.getInt(offset + 9), // kind
            cursor.getInt(offset + 10), // state
            new java.util.Date(cursor.getLong(offset + 11)) // modify_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TableRecordPersonal entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCloud_id(cursor.getLong(offset + 1));
        entity.setDetail(cursor.getString(offset + 2));
        entity.setMoney(cursor.getFloat(offset + 3));
        entity.setBuy_time(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setCategory_id(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setCategory_name(cursor.getString(offset + 6));
        entity.setBuyer_id(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setBuyer(cursor.getString(offset + 8));
        entity.setKind(cursor.getInt(offset + 9));
        entity.setState(cursor.getInt(offset + 10));
        entity.setModify_time(new java.util.Date(cursor.getLong(offset + 11)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TableRecordPersonal entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TableRecordPersonal entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
